### ISSUE TITLE
Problems checking if .cvs file is provided

### ISSUE THREAD

**Issue by Pippetta87** [johnnytam100/pdb2uniprot#1]
Hi,
I have to replace with input.endswith('.cvs') since otherwise I get:

```
python ~/src/pdb2uniprot/pdb2uniprot_tam.py --input pdb2uniprot.cvs --pdb_col PDB_ID --chain_col CHAIN_ID
/home/myuser//src/pdb2uniprot/pdb2uniprot_tam.py:16: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
pdb2uniprot.cvs
Traceback (most recent call last):
  File "/home/myuser//src/pdb2uniprot/pdb2uniprot_tam.py", line 50, in <module>
    pdb_chain_df.columns = ['pdb','chain']
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/bio/lib/python3.11/site-packages/pandas/core/generic.py", line 6307, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/myuser/bio/lib/python3.11/site-packages/pandas/core/generic.py", line 813, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/myuser/bio/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 239, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/myuser/bio/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

**Comment by johnnytam100** [comment]
Thanks! @Pippetta87

**Comment by johnnytam100** [comment]
Thanks! @Pippetta87
